#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TAILBENCH_DIR="$REPO_ROOT/deps/Tailbench"
SUITE_DIR="$TAILBENCH_DIR/tailbench"
DEFAULT_DATA_ROOT="${SEMATUNE_TAILBENCH_DATA_ROOT:-/mydata/SemaTune-tailbench/tailbench.inputs}"
DATA_ROOT="$DEFAULT_DATA_ROOT"
DATA_ROOT_EXPLICIT=0
WITH_INPUTS=1
INPUT_ARCHIVE=''
EXPECTED_COMMIT=2f3098b539a9a3413086fc77e29637937bafd116

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_tailbench.sh
  scripts/setup_tailbench.sh [--data-root DIR]
  scripts/setup_tailbench.sh --without-inputs

Build the pinned TailBench harness and the four SemaTune paper workloads:
Masstree, Silo, Sphinx, and Xapian. By default, missing runtime inputs are
downloaded and safely extracted under /mydata/SemaTune-tailbench/tailbench.inputs.

Options:
  --with-inputs                 Install inputs (default; retained for compatibility).
  --without-inputs              Build software only.
  --accept-unverified-inputs    Deprecated compatibility flag; no longer required.
  --input-archive FILE          Use an existing archive instead of downloading.
  --data-root DIR               Input destination (default under /mydata).
  -h, --help

The upstream 10.23 GB archive has no publisher cryptographic digest; its locked
byte size and safe archive layout are validated. This script does not run a benchmark.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-inputs) WITH_INPUTS=1; shift ;;
    --without-inputs) WITH_INPUTS=0; shift ;;
    --accept-unverified-inputs) shift ;;
    --input-archive)
      [[ $# -ge 2 && -n "$2" ]] || { echo '--input-archive requires FILE.' >&2; exit 2; }
      INPUT_ARCHIVE="$2"; shift 2
      ;;
    --data-root)
      [[ $# -ge 2 && -n "$2" ]] || { echo '--data-root requires DIR.' >&2; exit 2; }
      DATA_ROOT="$2"; DATA_ROOT_EXPLICIT=1; shift 2
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ "$WITH_INPUTS" -eq 0 && ( -n "$INPUT_ARCHIVE" || "$DATA_ROOT_EXPLICIT" -eq 1 ) ]]; then
  echo '--input-archive and --data-root cannot be combined with --without-inputs.' >&2
  exit 2
fi
[[ "$(uname -s)" == Linux ]] || { echo 'TAILBENCH_SETUP: FAIL: Linux is required.' >&2; exit 1; }
[[ "$(dpkg --print-architecture)" == amd64 ]] || {
  echo 'TAILBENCH_SETUP: FAIL: the pinned artifact requires amd64.' >&2; exit 1;
}
if [[ -r /etc/os-release ]]; then
  # shellcheck disable=SC1091
  source /etc/os-release
  if [[ "${ID:-}" != ubuntu || "${VERSION_ID:-}" != 22.04 ]]; then
    echo "TAILBENCH_SETUP: FAIL: Ubuntu 22.04 is required (found ${PRETTY_NAME:-unknown})." >&2
    exit 1
  fi
fi

ROOT=()
if [[ "$(id -u)" -ne 0 ]]; then
  sudo -n true >/dev/null 2>&1 || {
    echo 'TAILBENCH_SETUP: FAIL: root or non-interactive sudo is required.' >&2
    exit 1
  }
  ROOT=(sudo -n)
fi

echo 'Installing TailBench build dependencies...'
"${ROOT[@]}" apt-get update
"${ROOT[@]}" env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  autoconf automake bison build-essential ca-certificates git libaio-dev \
  libboost-all-dev libbz2-dev libdb5.3++-dev libgoogle-perftools-dev \
  libjemalloc-dev liblz4-dev liblzma-dev libnuma-dev libreadline-dev libssl-dev \
  libtool libtool-bin pkg-config python3 sox swig uuid-dev zlib1g-dev

if [[ ! -f "$TAILBENCH_DIR/README.md" ]]; then
  [[ -d "$REPO_ROOT/.git" || -f "$REPO_ROOT/.git" ]] || {
    echo 'TAILBENCH_SETUP: FAIL: TailBench is absent from this archive.' >&2
    echo 'Use the recursively materialized Zenodo archive or a Git checkout.' >&2
    exit 1
  }
  git -C "$REPO_ROOT" submodule update --init --recursive -- deps/Tailbench
fi
[[ -f "$TAILBENCH_DIR/README.md" ]] || {
  echo 'TAILBENCH_SETUP: FAIL: materializing deps/Tailbench did not produce README.md.' >&2
  exit 1
}
if [[ -e "$TAILBENCH_DIR/.git" ]]; then
  actual_commit="$(git -C "$TAILBENCH_DIR" rev-parse HEAD)"
  [[ "$actual_commit" == "$EXPECTED_COMMIT" ]] || {
    echo "TAILBENCH_SETUP: FAIL: TailBench is at $actual_commit, expected $EXPECTED_COMMIT." >&2
    exit 1
  }
fi

DATA_ROOT="$(realpath -m "$DATA_ROOT")"
SCRATCH_DIR="$TAILBENCH_DIR/scratch"
mkdir -p "$SCRATCH_DIR"
{
  echo '# Generated by scripts/setup_tailbench.sh.'
  printf 'DATA_ROOT=%q\n' "$DATA_ROOT"
  printf 'JDK_PATH=%q\n' '/usr/lib/jvm/java-8-openjdk-amd64'
  printf 'SCRATCH_DIR=%q\n' "$SCRATCH_DIR"
} > "$SUITE_DIR/configs.sh"

jobs="$(nproc)"
echo 'Building TailBench integrated harness...'
make -C "$SUITE_DIR/harness" -j"$jobs" client.o tbench_server_integrated.o

echo 'Building TailBench Masstree...'
(
  cd "$SUITE_DIR/masstree"
  autoconf
  ./configure --disable-assertions --with-malloc=tcmalloc
  make -j"$jobs" mttest_integrated
)

echo 'Building TailBench Silo...'
(
  cd "$SUITE_DIR/silo/masstree"
  if [[ ! -f config.h ]]; then
    ./configure --disable-assertions --disable-invariants \
      --disable-preconditions --enable-max-key-len=1024 --with-malloc=jemalloc
  fi
)
make -C "$SUITE_DIR/silo" MODE=perf -j"$jobs" \
  out-perf.masstree/benchmarks/dbtest_integrated

echo 'Building TailBench Sphinx...'
(
  cd "$SUITE_DIR/sphinx"
  rm -rf sphinx-install
  rm -f client.o decoder.o decoder_integrated decoder_server_networked decoder_client_networked
  prefix="$PWD/sphinx-install"
  mkdir -p "$prefix"

  cd sphinxbase-5prealpha
  ./configure --prefix="$prefix" --without-python
  make -j"$jobs"
  make install
  test -f "$prefix/lib/pkgconfig/sphinxbase.pc"

  cd ../pocketsphinx-5prealpha
  PKG_CONFIG_PATH="$prefix/lib/pkgconfig" \
    CPPFLAGS="-I$prefix/include" LDFLAGS="-L$prefix/lib" \
    ./configure --prefix="$prefix" --without-python
  PKG_CONFIG_PATH="$prefix/lib/pkgconfig" make -j"$jobs"
  PKG_CONFIG_PATH="$prefix/lib/pkgconfig" make install
  test -f "$prefix/lib/pkgconfig/pocketsphinx.pc"

  cd ..
  PKG_CONFIG_PATH="$prefix/lib/pkgconfig" \
    LD_LIBRARY_PATH="$prefix/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
    make -j"$jobs" LDFLAGS="-pthread -lrt -Wl,-rpath,$prefix/lib"
)

echo 'Building TailBench Xapian...'
(
  cd "$SUITE_DIR/xapian/xapian-core-1.2.13"
  mkdir -p install
  ./configure --prefix="$PWD/install" CXXFLAGS='-std=c++98'
  make -j"$jobs"
  make install
)
(
  cd "$SUITE_DIR/xapian"
  rm -f main.o server.o client.o xapian_integrated xapian_networked_server \
    xapian_networked_client genTerms
  xapian_prefix="$PWD/xapian-core-1.2.13/install"
  xapian_libs="$("$xapian_prefix/bin/xapian-config" --libs)"
  make -j"$jobs" \
    LIBS="$xapian_libs -Wl,-rpath,$xapian_prefix/lib -lpthread -lrt"
)

if [[ "$WITH_INPUTS" -eq 1 ]]; then
  if [[ -d "$DATA_ROOT/sphinx/wav" && -f "$DATA_ROOT/xapian/terms.in" && -f "$DATA_ROOT/xapian/wiki/iamchert" ]]; then
    echo "TAILBENCH_INPUTS: already installed ($DATA_ROOT)"
  else
    data_parent="$(dirname "$DATA_ROOT")"
    if [[ ! -d "$data_parent" ]]; then
      "${ROOT[@]}" install -d -o "$(id -u)" -g "$(id -g)" "$data_parent"
    fi
    [[ -w "$data_parent" ]] || { echo "TailBench data parent is not writable: $data_parent" >&2; exit 1; }
    if [[ -z "$INPUT_ARCHIVE" ]]; then
      echo 'WARNING: downloading TailBench inputs without a publisher-provided digest.'
      python3 "$SCRIPT_DIR/fetch_artifact_inputs.py" record tailbench-inputs --root "$REPO_ROOT"
      INPUT_ARCHIVE="$REPO_ROOT/downloads/tailbench.inputs.tgz"
    fi
    INPUT_ARCHIVE="$(realpath -m "$INPUT_ARCHIVE")"
    python3 "$SCRIPT_DIR/install_tailbench_inputs.py" \
      --archive "$INPUT_ARCHIVE" --data-root "$DATA_ROOT"
  fi

  config_data_path="$TAILBENCH_DIR/tailbench.inputs"
  if [[ -L "$config_data_path" ]]; then
    ln -sfn "$DATA_ROOT" "$config_data_path"
  elif [[ ! -e "$config_data_path" ]]; then
    ln -s "$DATA_ROOT" "$config_data_path"
  elif [[ "$(realpath "$config_data_path")" != "$DATA_ROOT" ]]; then
    echo "TAILBENCH_SETUP: FAIL: config input path already exists: $config_data_path" >&2
    echo "Move it aside or select it with --data-root before rerunning setup." >&2
    exit 1
  fi
fi

VALIDATE_ARGS=(
  --tailbench-root "$SUITE_DIR"
  --data-root "$DATA_ROOT"
)
if [[ "$WITH_INPUTS" -eq 1 ]]; then
  VALIDATE_ARGS+=(--require-inputs)
fi
python3 "$SCRIPT_DIR/validate_tailbench_setup.py" "${VALIDATE_ARGS[@]}"

echo 'TAILBENCH_SETUP: PASS'
echo "  Source: $SUITE_DIR"
echo '  Workloads: masstree silo sphinx xapian'
if [[ "$WITH_INPUTS" -eq 1 ]]; then
  echo "  Inputs: $DATA_ROOT"
else
  echo '  Inputs: not requested (Masstree and Silo are runnable without them)'
fi
